apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/talesrc/platform-lab.git
    targetRevision: main
    path: charts/platform-gateway
    helm:
      valuesObject:
        routes:
          - name: argocd
            namespace: argocd
            hostname: argocd.lab.localhost
            service: argocd-server
            port: 80
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
