apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: {{ .Values.gatewayClass.name }}
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: {{ .Values.gateway.name }}-proxy
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.gateway.http.port }}
      allowedRoutes:
        namespaces:
          {{- if and .Values.gateway.https.enabled .Values.gateway.redirectHttpToHttps }}
          from: Same
          {{- else }}
          {{- include "platform-gateway.platformNamespaces" . | nindent 10 }}
          {{- end }}
    {{- with .Values.gateway.https }}
    {{- if .enabled }}
    - name: https
      protocol: HTTPS
      port: {{ .port }}
      hostname: {{ .hostname | quote }}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ .certificate.secretName }}
      allowedRoutes:
        namespaces:
          {{- include "platform-gateway.platformNamespaces" $ | nindent 10 }}
    {{- with $.Values.gateway.appsListener }}
    {{- if .enabled }}
    - name: {{ .name }}
      protocol: HTTPS
      port: {{ $.Values.gateway.https.port }}
      hostname: {{ .hostname | quote }}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ .certificate.secretName }}
      allowedRoutes:
        {{- toYaml .allowedRoutes | nindent 8 }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
