apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: podinfo
  labels:
    app.kubernetes.io/name: podinfo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: podinfo
