apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
  labels:
    app.kubernetes.io/name: ${{ values.name }}
    app.kubernetes.io/part-of: apps
spec:
  selector:
    app.kubernetes.io/name: ${{ values.name }}
  ports:
    - name: http
      port: 80
      targetPort: http
