apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello
  labels:
    app.kubernetes.io/name: hello
    app.kubernetes.io/part-of: apps
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hello
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
